version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Minio:Root:User=minioadmin
      - Minio:Root:Password=minioadmin
      - AccessConfiguration:Url=http://localhost:9001/api/v1/service-account-credentials
      - AccessConfiguration:AccessKey=iuy2ccJjSFYcCYYuTGpH
      - AccessConfiguration:SecretKey=AAClPOqua2REZUgXS6IBnnnwRo19ZdswUY3RnhG4
      - AccessConfiguration:Api=s3v4
      - AccessConfiguration:Path=auto
      - AccessConfiguration:Endpoint=http://localhost:9000
    ports:
      - "8080"
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data
    command: server --console-address :9001 /data 